version: "3.9"
services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ${DB_VOLUME}:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
    be:
        build: ./Backend
        container_name: be
        depends_on:
            - db
        ports:
            - ${BE_PORT}:5000
    fe:
        build: ./Frontend/eco-web
        container_name: fe
        depends_on:
            - db
            - be
        ports:
            - ${FE_PORT}:3000
